name: Hello World
on: [push]
jobs:
  meu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt