name: Hello World
on: [push]
jobs:
  meu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Cache Do PIP
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Listar Arquivos do REPOsitorio
        run: |
          ls -la
          ls -la conversor || true
      - name: Rodar Testes
        env:
          PYTHONPATH: .
        run: pytest -q --junit-xml=pytest-report.xml

      - name: Upload do Relatorio
        uses: actions/upload-artifact@v4
        with:
          name: 'pytest-report'
          path: pytest-report.xml
