name: Hello World
on: [push]
jobs:
  meu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Listar Arquivos do REPOsitorio
        run: |
          ls -la
          ls -la conversor || true
